services:

  samuro-db:
    image: postgres:14
    restart: always
    ports:
      - "45436:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-samuro}
      POSTGRES_DB: ${POSTGRES_DB:-samuro}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1121}
    volumes:
     - postgres_data:/var/lib/postgresql/data
    networks:
      - private

  samuro:
    build:
        context: .
        dockerfile: Dockerfile
        args:
          postgres_version: ${POSTGRES_VERSION:-14}
    command: ["python3.10", "-O", "main.py"]
    env_file:
      - .env
    depends_on:
      - samuro-db
    restart: always
    networks:
      - private

networks:
  private:
    external: false

volumes:
  postgres_data:
